# Site settings
author: Eric Loudon
title: A Functional Blog
header-img: img/home-bg.png
email: loudon.eric@gmail.com
copyright_name: Eric Loudon
description: > # this means to ignore newlines until "baseurl:"
  It does it's job. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eloudon

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
